package main

import (
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	_ "github.com/robstave/meowmorize/docs" // Import the docs generated by Swag
	"github.com/robstave/meowmorize/internal/adapters/controller"
	"github.com/robstave/meowmorize/internal/adapters/repositories"
	"github.com/robstave/meowmorize/internal/domain"
	"github.com/robstave/meowmorize/internal/domain/types"
	"github.com/robstave/meowmorize/internal/logger"
	httpSwagger "github.com/swaggo/echo-swagger" // Import Swagger middleware
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// @title MeowMorize Flashcard API
// @version 1.0
// @description API documentation for the MeowMorize Flashcard App.
// @host 192.168.86.176:8789
// @BasePath /api
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	// Initialize Logger
	slogger := logger.InitializeLogger()
	logger.SetLogger(slogger) // Optional: If you prefer setting a package-level logger

	// Initialize Database
	dbPath := "./meowmerize.db"
	if path := os.Getenv("DB_PATH"); path != "" {
		dbPath = path
	}
	slogger.Info("DBPath set", "dbpath", dbPath)

	db, err := gorm.Open(sqlite.Open(dbPath), &gorm.Config{})
	if err != nil {
		slogger.Error("Failed to connect to database", "path", dbPath, "error", err)
		log.Fatalf("Failed to connect to database: %v", err)
	}

	err = db.AutoMigrate(&types.Deck{}, &types.Card{}, &types.User{})
	if err != nil {
		slogger.Error("Failed to migrate database", "error", err)
		log.Fatalf("Failed to migrate database: %v", err)
	}

	// Initialize Repositories
	deckRepo := repositories.NewDeckRepositorySQLite(db)
	cardRepo := repositories.NewCardRepositorySQLite(db)
	userRepo := repositories.NewUserRepositorySQLite(db) // Initialize User Repository

	// Initialize Service
	service := domain.NewService(slogger, deckRepo, cardRepo, userRepo)

	// Initialize Controller
	meowController := controller.NewMeowController(service, slogger)

	// Initialize Echo
	e := echo.New()

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())

	e.Use(middleware.CORS())
	/*
		e.Use(middleware.CORSWithConfig(middleware.CORSConfig{
			AllowOrigins: []string{"*", "http://localhost:8789", "http://192.168.86.176:8789", "http://localhost:3000"}, // Update as needed
			AllowMethods: []string{echo.GET, echo.POST, echo.PUT, echo.DELETE, echo.OPTIONS},
			AllowHeaders: []string{
				"Content-Type",
				"Authorization",
			},
		}))
	*/

	// Routes
	api := e.Group("/api")
	deckGroup := api.Group("/decks")
	sessionGroup := api.Group("/sessions")
	cardGroup := api.Group("/cards")

	// Authentication Route
	api.POST("/login", meowController.Login)

	// Protected Routes
	// Define a JWT middleware
	JWTSecret := controller.JWTSecret
	jwtMiddleware := middleware.JWTWithConfig(middleware.JWTConfig{
		SigningKey: JWTSecret,
	})

	// Protect deck, card, and session routes
	protectedDeckGroup := deckGroup.Group("", jwtMiddleware)
	protectedDeckGroup.GET("", meowController.GetAllDecks)
	protectedDeckGroup.POST("/default", meowController.CreateDefaultDeck)
	protectedDeckGroup.GET("/:id", meowController.GetDeckByID)
	protectedDeckGroup.POST("", meowController.CreateDeck)
	protectedDeckGroup.PUT("/:id", meowController.UpdateDeck)
	protectedDeckGroup.DELETE("/:id", meowController.DeleteDeck)
	protectedDeckGroup.POST("/import", meowController.ImportDeck)
	protectedDeckGroup.GET("/export/:id", meowController.ExportDeck)
	protectedDeckGroup.POST("/stats/:id", meowController.ClearDeckStats)
	protectedDeckGroup.POST("/collapse", meowController.CollapseDecks) // Add this line

	protectedCardGroup := cardGroup.Group("", jwtMiddleware)
	protectedCardGroup.POST("/stats", meowController.UpdateCardStats)
	protectedCardGroup.GET("/:id", meowController.GetCardByID)
	protectedCardGroup.POST("", meowController.CreateCard)
	protectedCardGroup.PUT("/:id", meowController.UpdateCard)
	protectedCardGroup.DELETE("/:id", meowController.DeleteCard)

	protectedSessionGroup := sessionGroup.Group("", jwtMiddleware)
	protectedSessionGroup.POST("/start", meowController.StartSession)
	protectedSessionGroup.GET("/next", meowController.GetNextCard)
	protectedSessionGroup.DELETE("/clear", meowController.ClearSession)
	protectedSessionGroup.GET("/stats", meowController.GetSessionStats)

	// Swagger endpoint
	e.GET("/swagger/*", httpSwagger.WrapHandler)

	// Serve React Frontend
	// Define the path to your React build directory
	reactBuildPath := "./meowmorize-frontend/build"

	// Serve static files
	e.Static("/", reactBuildPath)

	// Catch-all route to serve index.html for client-side routing
	e.GET("/*", func(c echo.Context) error {
		// Prevent Echo from serving API routes with this handler
		if strings.HasPrefix(c.Request().URL.Path, "/api/") {
			return c.NoContent(http.StatusNotFound)
		}
		return c.File(reactBuildPath + "/index.html")
	})

	// Start Server
	port := "8789"
	if p := os.Getenv("PORT"); p != "" {
		port = p
	}
	slogger.Info("Starting server", "port", port)
	if err := e.Start(":" + port); err != nil && err != http.ErrServerClosed {
		slogger.Error("Shutting down the server", "error", err)
		log.Fatalf("Shutting down the server: %v", err)
	}
}
