package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"

	"github.com/joho/godotenv"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	_ "github.com/robstave/meowmorize/docs" // Import the docs generated by Swag
	"github.com/robstave/meowmorize/internal/adapters/controller"
	"github.com/robstave/meowmorize/internal/adapters/repositories"
	"github.com/robstave/meowmorize/internal/domain"
	"github.com/robstave/meowmorize/internal/domain/types"
	"github.com/robstave/meowmorize/internal/logger"
	httpSwagger "github.com/swaggo/echo-swagger" // Import Swagger middleware
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// @title MeowMorize Flashcard API
// @version 1.0
// @description API documentation for the MeowMorize Flashcard App.
// @BasePath /api
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
func main() {
	// Load environment variables
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found")
	}

	// Initialize Logger
	slogger := logger.InitializeLogger()
	logger.SetLogger(slogger) // Optional: If you prefer setting a package-level logger

	// Initialize Database
	dbPath := "./meowmerize.db"
	if path := os.Getenv("DB_PATH"); path != "" {
		dbPath = path
	}
	slogger.Info("DBPath set", "dbpath", dbPath)

	db, err := gorm.Open(sqlite.Open(dbPath), &gorm.Config{})
	if err != nil {
		slogger.Error("Failed to connect to database", "path", dbPath, "error", err)
		log.Fatalf("Failed to connect to database: %v", err)
	}

	err = db.AutoMigrate(&types.Deck{}, &types.Card{}, &types.User{}, &types.SessionLog{})
	if err != nil {
		slogger.Error("Failed to migrate database", "error", err)
		log.Fatalf("Failed to migrate database: %v", err)
	}

	// Initialize LLM Repository
	apiKey := os.Getenv("GOOGLE_API_KEY")
	model := os.Getenv("GOOGLE_MODEL")
	if model == "" {
		model = "gemini-pro" // default model
	}
	llmRepo, err := repositories.NewLLMRepositoryLangChain(apiKey, model)
	if err != nil {
		slogger.Error("Failed to initialize LLM repository", "error", err)
		log.Fatalf("Failed to initialize LLM repository: %v", err)
	}

	// Initialize Repositories
	deckRepo := repositories.NewDeckRepositorySQLite(db)
	cardRepo := repositories.NewCardRepositorySQLite(db)
	userRepo := repositories.NewUserRepositorySQLite(db)
	sessionLogRepo := repositories.NewSessionLogRepositorySQLite(db)

	// Initialize Service
	service := domain.NewService(slogger, deckRepo, cardRepo, userRepo, sessionLogRepo, llmRepo)

	// Read JWT secret from environment
	jwtSecret := os.Getenv("JWT_SECRET")
	if jwtSecret == "" {
		slogger.Error("JWT_SECRET environment variable is required")
		log.Fatal("JWT_SECRET environment variable is required")
	}
	controller.InitJWTSecret(jwtSecret)

	// Initialize Controller
	meowController := controller.NewMeowController(service, slogger)

	// Initialize Echo
	e := echo.New()

	// Middleware
	e.Use(middleware.Logger())
	e.Use(middleware.Recover())
	e.Use(middleware.CORS())

	// Routes
	api := e.Group("/api")
	deckGroup := api.Group("/decks")
	sessionGroup := api.Group("/sessions")
	cardGroup := api.Group("/cards")

	// Authentication Route
	api.POST("/login", meowController.Login)

	// Protected Routes
	JWTSecret := controller.JWTSecret
	jwtMiddleware := middleware.JWTWithConfig(middleware.JWTConfig{
		SigningKey: JWTSecret,
	})

	adminGroup := api.Group("/admin", jwtMiddleware, controller.AdminMiddleware)

	// Protect deck, card, and session routes
	protectedDeckGroup := deckGroup.Group("", jwtMiddleware)
	protectedDeckGroup.GET("", meowController.GetAllDecks)
	protectedDeckGroup.POST("/default", meowController.CreateDefaultDeck)
	protectedDeckGroup.GET("/:id", meowController.GetDeckByID)
	protectedDeckGroup.POST("", meowController.CreateDeck)
	protectedDeckGroup.PUT("/:id", meowController.UpdateDeck)
	protectedDeckGroup.DELETE("/:id", meowController.DeleteDeck)
	protectedDeckGroup.POST("/import", meowController.ImportDeck)
	protectedDeckGroup.GET("/export/:id", meowController.ExportDeck)
	protectedDeckGroup.POST("/stats/:id", meowController.ClearDeckStats)
	protectedDeckGroup.POST("/collapse", meowController.CollapseDecks)

	protectedCardGroup := cardGroup.Group("", jwtMiddleware)
	protectedCardGroup.POST("/stats", meowController.UpdateCardStats)
	protectedCardGroup.POST("/explain/:id", meowController.ExplainCard)
	protectedCardGroup.GET("/explain/status", meowController.GetLLMStatus)
	protectedCardGroup.GET("/:id", meowController.GetCardByID)
	protectedCardGroup.POST("/:id", meowController.CreateCard)
	protectedCardGroup.PUT("/:id", meowController.UpdateCard)
	protectedCardGroup.DELETE("/:id", meowController.DeleteCard)

	protectedSessionGroup := sessionGroup.Group("", jwtMiddleware)
	protectedSessionGroup.POST("/start", meowController.StartSession)
	protectedSessionGroup.GET("/next", meowController.GetNextCard)
	protectedSessionGroup.DELETE("/clear", meowController.ClearSession)
	protectedSessionGroup.GET("/stats", meowController.GetSessionStats)

	protectedSessionGroup.GET("/overview/:id", meowController.GetSessionOverview)

	// Get all logs for a given session:
	protectedSessionGroup.GET("/:session_id", meowController.GetSessionLogs)

	// Get distinct session log IDs for a user (optionally by deck):
	protectedSessionGroup.GET("/ids", meowController.GetSessionLogIds)

	userGroup := api.Group("/user", jwtMiddleware)
	userGroup.PUT("/password", meowController.ChangePassword)

	adminGroup.GET("/users", meowController.AdminGetAllUsers)
	adminGroup.POST("/users", meowController.AdminCreateUser)
	adminGroup.DELETE("/users/:id", meowController.AdminDeleteUser)

	// Swagger endpoint
	e.GET("/swagger/*", httpSwagger.WrapHandler)

	// Serve React Frontend
	// Define the path to your React build directory
	reactBuildPath := "./meowmorize-frontend/build"

	// Serve static files
	e.Use(middleware.Static(reactBuildPath))

	// Catch-all route to serve index.html for client-side routing
	e.GET("/*", func(c echo.Context) error {
		slogger.Info("other url", "path", c.Request().URL.Path)
		// Prevent Echo from serving API routes with this handler
		if strings.HasPrefix(c.Request().URL.Path, "/api/") {
			return c.NoContent(http.StatusNotFound)
		}
		path := c.Request().URL.Path

		// Redirect /swagger to /swagger/index.html#/
		if path == "/swagger" || path == "/swagger/" {
			return c.Redirect(http.StatusFound, "/swagger/index.html#/")
		}

		slogger.Info("other url2: " + reactBuildPath + "/index.html")
		return c.File(reactBuildPath + "/index.html")
	})

	// Start Server
	port := os.Getenv("PORT")
	if port == "" {
		port = "8789"
	}
	serverAddress := fmt.Sprintf(":%s", port)
	slogger.Info("Starting server", "address", serverAddress)
	if err := e.Start(serverAddress); err != nil && err != http.ErrServerClosed {
		slogger.Error("Shutting down the server", "error", err)
		log.Fatalf("Shutting down the server: %v", err)
	}
}
