## version: '3.8'

services:
  meowmorize:
    build:
      context: .
      dockerfile: Dockerfile  # Your combined Dockerfile
    container_name: meowmorize
    ports:
      - "8999:8999"  # Expose the port that your Go app listens on (set to 8999 in this example)
    environment:
      - DB_PATH=/app/data/db.sqlite3
      # Other environment variables as needed
    volumes:
      - db-data:/app/data  # Persist your SQLite data
    restart: unless-stopped

volumes:
  db-data:
    driver: local
